### ISSUE TITLE
The OMDB Api isn't open now

### ISSUE THREAD

**Issue by rakhi2104** [bradtraversy/movieinfo#1]
Is there an alternate Open API available ?

**Comment by rbhatia46** [comment]
You can go with TMDB(The Movie DB)

**Comment by rakhi2104** [comment]
There are different alternatives for OMDB. So closing this issue :+1:

**Comment by rakhi2104** [comment]
Thanks to #4 for enlightening me with the OMDB's free API Key with a 1000 Request per day limit.
