### ISSUE TITLE
Free Api key

### ISSUE THREAD

**Issue by ogzavc** [bradtraversy/movieinfo#4]
Hello to all,

If you need api key to make this work, you can get yours from here : http://www.omdbapi.com/apikey.aspx?
Free key has 1000 query per day, i think this is enought for test your project

When you get the key, Your get command will be like this 

axios.get('http://www.omdbapi.com/?t='+searchText+'&apikey=yourkeyhere')

**Comment by Jo1910** [comment]
Hi, I did the same and whatever I type in search box I get the error 'movie not found':

data: {…}
​​
Error: "Movie not found!"
​​
Response: "False"
